spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: product-client
            client-authentication-method: none  # No client secret for public clients
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/product-realm